### ISSUE TITLE
python support

### ISSUE THREAD

**Issue by yaron-shamul** [noxone/regex-generator#170]
would you consider support some python code?
if you some help with itegrate with python I actually can help you  happily

**Comment by lars-sh** [comment]
@yaron-shamul, in order to prepare a Pull Request I'd need to know how Python handles regular expressions. Is the below example correct?

```Python
import re

def useRegex(input):
    pattern = re.compile(r"regex pattern")
    return pattern.match(input, re.IGNORECASE, re.MULTILINE, re.DOTALL)
```

**Comment by yaron-shamul** [comment]
yeah, it looks good

**Comment by noxone** [comment]
@preview

**Comment by noxone** [comment]
Python should be available now.
