### ISSUE TITLE
dot-stars in the wrong order

### ISSUE THREAD

**Issue by wvstolzing** [noxone/regex-generator#198]
**Describe the bug**
Whenever the generated regex needs to (greedy) repeat a single character, the `.*` that it's supposed to generate comes out as `*.`

**To Reproduce**
The most straightforward way to reproduce the error is to select some single characters in step 2. It appears when selecting other spans as well.

**Expected behavior**
Generated regex should've had `.*` in place of `*.`

**Screenshots**
![Screenshot from 2022-02-10 01-52-48](https://user-images.githubusercontent.com/2300956/153304190-0495b297-0412-47c6-8d00-49a9aa677e13.png)
reenshots**

**Desktop (please complete the following information):**
 - OS: Fedora 35
 - Browser: Firefox
 - Version: 96.0.3

**Comment by noxone** [comment]
Fixed with #199
