### ISSUE TITLE
Python sample code is wrong, including the regex.

### ISSUE THREAD

**Issue by ableunable** [noxone/regex-generator#259]
**Describe the bug**
The code generated for Python, in section 4, has some mistakes and the regex pattern is also functionally different from the one displayed in section 3.
For the sample `[]` in section 1, with the "Square brackets" selection in section 2: 
the regex in section 3 says: `\[\]`;
the Python code in section 4 says:
```
import re

def useRegex(input):
    pattern = re.compile(r"\\[\\]", re.IGNORECASE)
    return pattern.match(input)
```
 - The Python code issue is that `input` is a keyword and should not be used as a variable name (even though the code does work this way).
 - The regex issue is that the extra backslash is unnecessary because the string is already a r-string (raw string).

**To Reproduce**
Steps to reproduce the behaviour:
1\) Make an expression that requires a character to be escaped with a backslash;
2\) Scroll down and view the Python code; copy it and use it in Python;
3\) Notice that the r-string part `\\` is interpreted by Python as `\\`, instead of `\`.

**Expected behaviour**
The expected behaviour is that the Python code either uses a normal instead of r-string, or uses a r-string and does not try to unnecessarily escape the backslash. In the latter option, the same regex text as in section 3 should be used.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Firefox
 - Version: 103.0.2

**Comment by noxone** [comment]
Hi @ableunable , 
thank you for opening the issue.
My Python knowledge is quite limited. So it would be great if you could help me improve the generated code snippet.

It sounds like `input` is some kind of reserved word or should just not be used here. Which variable name would be better? What about `text` or maybe `inputText`?

And I just googled the r-strings a bit more... it seems that there is no escaping needed at all, is it?

So, for the regex `\["\]`, would this code be better? 
```python
import re

def useRegex(inputText):
    pattern = re.compile(r"\["""\]", re.IGNORECASE)
    return pattern.match(inputText)
```
(I added the quotation mark to include something where an escape sequence is required)

**Comment by ableunable** [comment]
Good looking out with the quotation mark! Yes, I believe `r"\["'"'r"\]"` will work. In fact, I checked it right now. The regex compiles and it matches properly. Although, `r"\[\"\]"` works just as well - actually escaping the quotation mark so as not to close the string, and it looks a bit tidier in my opinion.

I don't know much about regex myself, I just happened to come across this problem while working on some program. But I imagine that anything that needs to be escaped within regex will work the same way as the bracket does.

Regarding `input`, that's the keyword used to get input from stdin. So you could write `a = input("Name: ")`, and that would output `Name: `, prompting for input to assign to the variable `a`. The `useRegex` function _does_ work with `input` as the name of the parameter, but it's generally not recommended to use keywords in that way.

On a more aesthetic note, pythonistas prefer 'snake case' over 'camel case'. So `inputText` and `useRegex` would become `input_text` and `use_regex`.

Hope this was helpful!

**Comment by noxone** [comment]
Thank you for the input. I just renamed the variable and method. 
And I also just tried different string in this online python interpreter: https://www.programiz.com/python-programming/online-compiler/
The `r"\[\"\]"` seems to work, yes. It looks a bit easier and tidier, so I will change the code to generate the code you suggested.

**Comment by noxone** [comment]
Fixed. Thank you for filing this bug report!

**Comment by ableunable** [comment]
Sorry if it's not alright to comment on a closed issue, but I just tested it on the site. All works well, except for when I input `\`. Then the Python code has `r""'\\\\'` in it, when it could simply have `r"\\"` (escaping is still necessary for the backslash character itself).

Although I don't know much about regex, from what I see, I think that the Python string should always be exactly the same one as the general regex one, *except* for escaping backslashes and quotation marks.

**Comment by noxone** [comment]
Hi, indeed. This is a case that the code does not yet handle good.
From what I read about the r-strings, they cannot have an odd number of backslashes in the end (because of the escaped quotation mark). So I made my life easy by placing all backslashes at the end of the pattern in an additional (non-r-)string.
You're right: The current behavior is not pretty. I'll try to fix:
- The empty r-string in the beginning (in case that's the correct behavior)
- Unnecessary new string for an even number of backslashes

**Comment by noxone** [comment]
OK, I published the changes. 
Now there is still one bug, I think: The regex `\\\\"` results in python code `r"\\\\\""` which is not correct. So the double quotation marks need to be escaped differently.
So, I think I will use a kind of string for this again...

**Comment by ableunable** [comment]
If it'll simplify your work, another option would be to not use r-strings and just escape anything that needs to be escaped, in a normal string.  
Python sees `r"\""` as `'\\"'` anyway.

**Comment by noxone** [comment]
OK, I hope it's now fixed (once the deployment is done).

**Comment by noxone** [comment]
So. for me it looks, like it's working now. If there are `"` and `'` in the same regex it gets a little confusing, but I don't think that can be avoided if you have to escape characters.
Is it OK for you to close this issue?
