### ISSUE TITLE
Full Docker based build fails on unit tests

### ISSUE THREAD

**Issue by noxone** [noxone/regex-generator#261]
**Describe the bug**
The gradle build inside a docker container fails when running the unit tests.

**To Reproduce**
Simply follow the steps from the README file
1. Clone the repository
2. Navigate into the project's root folder
3. Run `docker build . -t noxone/regexgenerator`
4. See error:
```
> Task :browserTest
Cannot start FirefoxHeadless

Command '/usr/bin/firefox' requires the firefox snap to be installed.
Please install it with:

snap install firefox
FirefoxHeadless stdout:
FirefoxHeadless stderr: 
Command '/usr/bin/firefox' requires the firefox snap to be installed.
Please install it with:

snap install firefox
Cannot start FirefoxHeadless

Command '/usr/bin/firefox' requires the firefox snap to be installed.
Please install it with:

snap install firefox
FirefoxHeadless stdout:
FirefoxHeadless stderr: 
Command '/usr/bin/firefox' requires the firefox snap to be installed.
Please install it with:

snap install firefox
Cannot start FirefoxHeadless

Command '/usr/bin/firefox' requires the firefox snap to be installed.
Please install it with:

snap install firefox
FirefoxHeadless stdout:
FirefoxHeadless stderr: 
Command '/usr/bin/firefox' requires the firefox snap to be installed.
Please install it with:

snap install firefox
FirefoxHeadless failed 2 times (cannot start). Giving up.
java.lang.IllegalStateException: Errors occurred during launch of browser for testing.
- FirefoxHeadless
Please make sure that you have installed browsers.
Or change it via
browser {
    testTask {
        useKarma {
            useFirefox()
            useChrome()
            useSafari()
        }
    }
}

> Task :test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> Failed to execute all tests:
  :browserTest: java.lang.IllegalStateException: Errors occurred during launch of browser for testing.
  - FirefoxHeadless
  Please make sure that you have installed browsers.
  Or change it via
  browser {
      testTask {
          useKarma {
              useFirefox()
              useChrome()
              useSafari()
          }
      }
  }

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 17s
```

**Expected behavior**
The build should run without problems and the docker build command should create a usable image.

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.5.1 on an M1 mac (so arm64 platform)

**Additional context**
The "normal" build works.

**Comment by noxone** [comment]
@lab34 : I remember you added this docker build possibility a few months ago.
Currently I'm quite a bit puzzled how to get it to work again. I tried a few changes in the Dockerfile, but til now nothing helped. It would be great if you could have a look here, too. Thank you!

**Comment by lab34** [comment]
Hello,
oh, that's strange. I don't understand why it was working before and it's not working anymore.
If I build only the TEMP_BUILD_IMAGE, and if I run a terminal into it, I can see with cat /etc/lsb-release that the gradle:7.4.2 image is based on Ubuntu 22.04 LTS
And, as far as I can see, with Ubuntu 22.04, we need to install firefox with snap, not apt, or if we prefer, we need to add the mozilla ppa.
I will make some tests...

**Comment by lab34** [comment]
With the [help of this](https://www.reddit.com/r/Ubuntu/comments/i7ue26/is_there_a_way_to_use_the_nonsnap_version_of/) , I think I managed to make it works :-)
I will make a PR...

**Comment by lab34** [comment]
PR is here: https://github.com/noxone/regex-generator/pull/262

**Comment by noxone** [comment]
Oh, wow, great. Thank you very much.
