### ISSUE TITLE
Weird, weird character recognition issue that happened 𝘰𝘯𝘤𝘦

### ISSUE THREAD

**Issue by souza-victor** [noxone/regex-generator#277]
**Describe the bug**
When asked to generate a pattern to match a string plus a trailing underscore, the generator outputs a pattern that matches the string plus a hyphen.

I can't seem to reproduce this issue ever since I reloaded the page, but it consistently did as above as long as I didn't reload it.

**To Reproduce**
1. Go to '[](https://regex-generator.olafneumann.org)'.
2. Paste text sample `TX_RESP_Q008`.
3. To select the 'interesting parts', on the third line, click the first and second `Multiple characters`. Then, on the first line, click the first `Character (_)`, which refers to the third character of the string. Then, click the second 'Character (_)', which refers to the eigth character of the string.
4. See that the pattern generated is either `[a-zA-Z]+_[a-zA-Z]+-Q008` or `[a-zA-Z]+_[a-zA-Z]+-`, depending on if you select Generate only patterns' or not, which I did (these patterns were copied straight from the website using the 'Copy regex' button).

**Expected behavior**
The pattern should have looked like this: 
`[a-zA-Z]+_[a-zA-Z]+_`

**Screenshots**
Not necessary.

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - Browser: Edge 
 - Version: 105.0.1343.42

**Additional context**
It was the first URL I opened when launching Edge. I had previously used the website. I first generated the RegEx without the trailing underscore, then I switched to the program RStudio, where I used a the sub() function to replace that pattern on a string, but I realized that it kept the underscore, so I corrected the RegEx, reran the function, then came back to the website to select the second underscore, and that's when it happened. I opened the DevTools to copy the trailing underscore from the source and pasted it into Google to make sure that the Unicode was from an underscore, and not, maybe, a weird Unicode character that the generator would have recognized as a hyphen, but it was your run of the mill underscore(here's the character I copied: `_`)

**Comment by noxone** [comment]
Hi @souza-victor , thanks for filing this. This is indeed very weird. I can reproduce the problem in my development environment, too. But I cannot find an obvious reason for this. So I need to investigate further.
What really baffles me is the fact that the program behaves differently depending on whether the page has just been freshly loaded or whether there has been previous interaction with the text box.

**Comment by noxone** [comment]
Well, OK... in the end this was easier than expected.
The reason for this was some kind of unwanted "caching". 

Background: In order to enable editing the input while already having matches selected, newly recognized possible matches are compared to existing ones from the previous input. And in this case the comparison was not detailed enough. So the app mistakenly reused the previous match for the new input although the character hat changed.

**Comment by noxone** [comment]
So, please reload the generator... the problem is fixed :)
