### ISSUE TITLE
Erroneous lone quantifier brackets.

### ISSUE THREAD

**Issue by rokejulianlockhart** [noxone/regex-generator#375]
**Describe the bug**
[Inputting `[id]=[6]` into `rg_raw_input_text` generates `\[id]=\[[^\]]*]`](https://regex-generator.olafneumann.org/?sampleText=%5Bid%5D%3D%5B6%5D&flags=i&selection=6%7CSquare%20brackets), whereas it should generate `\[id\]=\[[^\]]*\]`, per https://stackoverflow.com/a/49111429/9731176 and Visual Studio Code.

**To Reproduce**
1. [Input `[id]=[6]` into `rg_raw_input_text`.](https://regex-generator.olafneumann.org/?sampleText=%5Bid%5D%3D%5B6%5D&flags=i&selection=6%7CSquare%20brackets)
2. Click on `rg_button_copy`.
3. Duplicate into the Find and replace field of Visual Studio Code.
4. See error:

**Screenshots:**
![[Visual Studio Code Insiders.](file://usr/bin/env -S tea code-insiders)](https://user-images.githubusercontent.com/42837531/225113795-55dedffb-dc14-4040-a053-ec732ff0f56f.png)

**Desktop:**
 - OS:
```powershell
PS /home/rokejulianlockhart> uname -a
Linux RQN6C6 6.2.2-1-default #1 SMP PREEMPT_DYNAMIC Thu Mar  9 06:06:13 UTC 2023 (44ca817) x86_64 x86_64 x86_64 GNU/Linux
```

 - Browser
```powershell
PS /home/rokejulianlockhart> firefox -v                                   
Mozilla Firefox 110.0.1
```

**Comment by noxone** [comment]
Hm, thanks for filing this.
Maybe this depends on the regex engine that is being used... But yes, I will change this to work with VS Code.
