### ISSUE TITLE
JavaScript-error

### ISSUE THREAD

**Issue by nguyendachuy** [noxone/regex-generator#380]
An error occurred with these details:
- Exception: `can't access property "i3c_1", t is undefined`
- Commit ID: `ff31f7729ea786ed917d48ce22c7c05069e9c652`
- UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0
- Vendor: 
- Language: en-US
- Platform: Win32
- CPU: Windows NT 10.0; Win64; x64
- TouchPoints: 0
- Plugins:
  - PDF Viewer
  - Chrome PDF Viewer
  - Chromium PDF Viewer
  - Microsoft Edge PDF Viewer
  - WebKit built-in PDF
- StackTrace: TypeError: can't access property "i3c_1", t is undefined
@https://regex-generator.olafneumann.org/regex-generator.js?commitId=ff31f7729ea786ed917d48ce22c7c05069e9c652:1:636683
us@https://regex-generator.olafneumann.org/regex-generator.js?commitId=ff31f7729ea786ed917d48ce22c7c05069e9c652:1:557225
@https://regex-generator.olafneumann.org/regex-generator.js?commitId=ff31f7729ea786ed917d48ce22c7c05069e9c652:1:637586
@https://regex-generator.olafneumann.org/regex-generator.js?commitId=ff31f7729ea786ed917d48ce22c7c05069e9c652:1:638599
@https://regex-generator.olafneumann.org/regex-generator.js?commitId=ff31f7729ea786ed917d48ce22c7c05069e9c652:1:625862
@https://regex-generator.olafneumann.org/regex-generator.js?commitId=ff31f7729ea786ed917d48ce22c7c05069e9c652:1:648438
@https://regex-generator.olafneumann.org/regex-generator.js?commitId=ff31f7729ea786ed917d48ce22c7c05069e9c652:1:643418
@https://regex-generator.olafneumann.org/regex-generator.js?commitId=ff31f7729ea786ed917d48ce22c7c05069e9c652:1:643426
654/i/ku/<@https://regex-generator.olafneumann.org/regex-generator.js?commitId=ff31f7729ea786ed917d48ce22c7c05069e9c652:1:584320

**Comment by noxone** [comment]
Hi, thank you for filing this bug.
I see this error popping up in the last days only, so it is probably related to the update to Kotlin 1.8.20.
I'm quite unsure, where it comes from, but I'll try...

**Comment by noxone** [comment]
OK, the reason is that different versions of the JS file produced by the compiler create different names for the field in the serialized JSON objects. And when reading this from the local storage the resulting JSON object does not fit to the generated JS code anymore.
Thus when accessing the values while generating the regex for you, we get this `undefined` as the field is now called differently.

Fix is being prepared.

**Comment by noxone** [comment]
I hope this issue is fixed now and wait if new reports are coming in.
