### ISSUE TITLE
JavaScript-error: Problem open page with Firefox 114.0.1 (64-Bit)

### ISSUE THREAD

**Issue by TomGPoint** [noxone/regex-generator#407]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by TomGPoint** [comment]
Hi ,
sorry , a bit lag of time because im on work .

Here ist what the Error debugger says when you open the page:

An error occurred with these details:
- Exception: `[Exception... "File error: Not found"  nsresult: "0x80520012
(NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame ::
https://regex-generator.olafneumann.org/regex-generator.js?commitId=eab10fbb3bfe2dcf1605f316a21d715e9128d4fd
:: <TOP_LEVEL> :: line 1"  data: no]`
- Commit ID: `eab10fbb3bfe2dcf1605f316a21d715e9128d4fd`
- UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0)
Gecko/20100101 Firefox/114.0
- Vendor:
- Language: de
- Platform: Win32
- CPU: Windows NT 10.0; Win64; x64
- TouchPoints: 0
- Plugins:
  - PDF Viewer
  - Chrome PDF Viewer
  - Chromium PDF Viewer
  - Microsoft Edge PDF Viewer
  - WebKit built-in PDF
- StackTrace: Li: [Exception... "File error: Not found"  nsresult:
"0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame ::
https://regex-generator.olafneumann.org/regex-generator.js?commitId=eab10fbb3bfe2dcf1605f316a21d715e9128d4fd
:: <TOP_LEVEL> :: line 1"  data: no]
Js@
https://regex-generator.olafneumann.org/regex-generator.js?commitId=eab10fbb3bfe2dcf1605f316a21d715e9128d4fd:1:107683
Li@
https://regex-generator.olafneumann.org/regex-generator.js?commitId=eab10fbb3bfe2dcf1605f316a21d715e9128d4fd:1:537257
ji@
https://regex-generator.olafneumann.org/regex-generator.js?commitId=eab10fbb3bfe2dcf1605f316a21d715e9128d4fd:1:536757


And that ist what I can see If I press F11

Uncaught NS_ERROR_FILE_NOT_FOUND:
    <anonymous> LocalStorageSettings.kt:35
    <anonymous> LocalStorageSettings.kt:36
    <anonymous> LocalStorageSettings.kt:58
    Bs LocalStorageSettings.kt:26
    Ps ApplicationSettings.kt:6
    zs regex-generator.js:1
    va LanguageAccordionCard.kt:57
    $a api.kt:56
    yl P6LanguageDisplay.kt:28
    oa RGView.kt:44
    ea RGController.kt:20
    Ni RegexGenerator.kt:30
    Ni RegexGenerator.kt:23
    Bi RegexGenerator.kt:16
regex-generator.js:1
<https://regex-generator.olafneumann.org/regex-generator.js?commitId=eab10fbb3bfe2dcf1605f316a21d715e9128d4fd>


Hope this can help you.





Am Di., 20. Juni 2023 um 10:19 Uhr schrieb Olaf Neumann <
***@***.***>:

**Comment by TomGPoint** [comment]
Here a hint of the unloaded file

 
    <script type="text/javascript" src="**regex-generator.js**?commitId=eab10fbb3bfe2dcf1605f316a21d715e9128d4fd"></script>

**Comment by noxone** [comment]
Hm, ok. When does it appear? Right when opening the page? Or later when you want to do something?

**Comment by noxone** [comment]
Indeed... the Coffee stuff creates errors... that's a pitty.
SO I will probably just remove it.

**Comment by TomGPoint** [comment]
Hi Olaf , sorry for the late response. 
I've realized that It has something to do with company intern FF configuration. The problem never appeared with chrome. And with an FF clean install the problem disappeared also. 
I could now use your tool and it works excellent.

Sorry for the inconvenience !

**Comment by noxone** [comment]
Thank you for the update. I will then close this issue.
