### ISSUE TITLE
Pattern starting with hyphen throws error in grep

### ISSUE THREAD

**Issue by IoLimmer** [noxone/regex-generator#506]
With grep, when you pass a pattern that starts with a hyphen, grep will misinterpret this as an option flag and throw an error. This doesn't seem to be accounted for on the site.

`grep -P -i "-[A-Za-z0-9]+" test.txt`

[Seen here](https://regex-generator.olafneumann.org/?sampleText=Model%20name%3A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20Intel(R)%20Xeon(R)%20w7-2495X&flags=Pi&selection=55%7CCharacter,56%7CAlphanumeric%20characters)

When passed on the terminal with lscpu I get this error:

```
grep: invalid option -- '['
Usage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
```

Admittedly this can be fixed easily by adding a backslash infront of the hyphen but I thought it was worth mentioning.

**Comment by noxone** [comment]
Hi @IoLimmer , thank you for filing this. I can reproduce the issue and will add a fix for that.
