### ISSUE TITLE
Create a JavaScript Package Of Visulizer

### ISSUE THREAD

**Issue by wisehackermonkey** [noxone/regex-generator#528]
Hello Noxone!

Ran across your great little app!

Been finding it super useful. 

### Suggestion:

# Create a `JavaScript Package` out of the visualizer.
Just this: ----v
![image](https://github.com/user-attachments/assets/71648b85-610f-41bd-8273-fc3243a8f6b4)

I've got a app which would really benefit from your fantasitc visualization.

This would be amazing!

If you could point me in the right direction files in your app, if your not up for turning it into a library.
Id love to take on rewriting it in javascript.
----------
Link to my app:
https://wisehackermonkey.github.io/text-processor-react/
Here's the regex builder I'm working on, which could benefit from your visualization

![image](https://github.com/user-attachments/assets/695aeecd-4354-4e66-9a3c-6ec7addce863)

Some Othing cool app related to you'res and mine
https://jex.im/regulex/#!flags=&re=%5E(a%7Cb)*%3F%24
![image](https://github.com/user-attachments/assets/ae80a9ff-df65-4dc5-b3e4-e7982ea0d5ed)

Much thanks!

**Comment by noxone** [comment]
Hi @wisehackermonkey ,

I'm not too familiar with JavaScript, so I probably won't create a library for the visualization. And I'm unsure if I can create the visualization in such a generic way that it can be useful for others.

Nevertheless: Feel free to adapt the code to your needs or to create a library on your own! I would be interested in the outcome.


What information do you need? I will just provide some links into the source code and you can tell me, if this helps:

- The actual recognizing of possible matches is done here: [RecognizerRegistry.kt#L101](https://github.com/noxone/regex-generator/blob/main/src/jsMain/kotlin/org/olafneumann/regex/generator/recognizer/RecognizerRegistry.kt#L101). The output is simply a list of all regex matches that have been found.
- The whole UI state (as well as the match selection stuff) is done in models, so it doesn't mix with the DOM or the regex code. The Regex stuff is quite complex, so I created a separate model for that, too.
- So, the [PatternRecognizerModel.kt](https://github.com/noxone/regex-generator/blob/main/src/jsMain/kotlin/org/olafneumann/regex/generator/model/PatternRecognizerModel.kt) takes the recognized matches and manages them together with user selection. This model also has some logic to keep selection even if the input changed. _Please note:_ At this point we will still only have a simple list of possible matches. Some of them are marked as "selected".
- Next, the [DisplayModel.kt#L28](https://github.com/noxone/regex-generator/blob/main/src/jsMain/kotlin/org/olafneumann/regex/generator/ui/model/DisplayModel.kt#L28) takes these recognized (and possibly selected) matches and computes so called "MatchPresenters". These contain the information, how matches can be grouped (for the UI) and which match can be selected at which position. So, these MatchPresenters are the a first connection to what is displayed for the user - and is based on the simple list of the previous model.
- The DisplayModel also contains the logic, how to distribute the MatchPresenters to each row [here](https://github.com/noxone/regex-generator/blob/main/src/jsMain/kotlin/org/olafneumann/regex/generator/ui/model/DisplayModel.kt#L133).
- The actual HTML and DOM stuff happens in [P2MatchPresenter.kt#L85](https://github.com/noxone/regex-generator/blob/main/src/jsMain/kotlin/org/olafneumann/regex/generator/ui/parts/P2MatchPresenter.kt#L85). Most of that is hidden behind some Kotlin libraries or some helper functions so you barely see any direct DOM interaction. But you probably understand, what's going on: Create new DIVs and replace the old ones...

For any more help, feel free to ask :)

**Comment by wisehackermonkey** [comment]
OMG this is super helpful.
especially the magic inside. [RecognizerRegistry.kt#L101](https://github.com/noxone/regex-generator/blob/main/src/jsMain/kotlin/org/olafneumann/regex/generator/recognizer/RecognizerRegistry.kt#L101)

all of this explanation is so good i made a pull request to add it to the readme.

thanks!

**Comment by noxone** [comment]
That's a good idea, thank you.
Merged :)
