### ISSUE TITLE
Add formatted regex for terminal usage.

### ISSUE THREAD

**Issue by ArneAnka** [noxone/regex-generator#85]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when trying to use regular expression with the terminal command `grep`.

**Describe the solution you'd like**
A copy-and paste Regex snippet for terminal use under the `Usage in programming languages` section

**Comment by noxone** [comment]
@ArneAnka Please check the website again. `grep` has been added as a language. Is this what you were thinking of?

**Comment by ArneAnka** [comment]
Fantastic! Awesome project

**Comment by noxone** [comment]
Great, thank you!
So I'll close this issue. If you have something else to be changed or added, feel free to open another issue.

**Comment by lars-sh** [comment]
@noxone, the escaping of `'` seems to be correct, but looks a bit weird. Can't you just replace to `\'` at https://github.com/noxone/regex-generator/blob/e124e75f7db8aacf097407f48b227664d4c7530e/src/main/kotlin/org/olafneumann/regex/generator/regex/CodeGenerator.kt#L206 instead?

**Comment by noxone** [comment]
@lars-sh  That actually doesn't work for me (on MacOS).
And according to [StackOverflow](https://stackoverflow.com/questions/1250079/how-to-escape-single-quotes-within-single-quoted-strings) you can't escape that single quote this way.

**Comment by lars-sh** [comment]
@noxone, it seems ' does not handle backslashes, while " does. As normallly I'm using ", I just didn't notice that until now.
